### ISSUE TITLE
Bug: Duplicate Multiple String generated on GoogleSheet

### ISSUE THREAD

**Issue by viralkachhadiya** [lukas-h/sheets_i18n#2]
![Screenshot_2024-09-24_at_5 01 23_PM](https://github.com/user-attachments/assets/ac43dbf4-d2dd-4656-b830-b374b76210e0)

**Comment by viralkachhadiya** [comment]
#3 @lukas-h 

LGTM

**Comment by lukas-h** [comment]
@viralkachhadiya closing this
